### ISSUE TITLE
Trojan also question about Borderlands 1 release

### ISSUE THREAD

**Issue by TeeWin** [lucasassislar/nucleuscoop#16]
First off, thanks for everything you've done! I've used your Split play program for a while and love it. Keep up the good work.

Problem/question:
Mcafee detected a Trojan when I unzipped your master files. Accidently downloaded that instead of release. In addition, do you intend to release another alpha version with Borderlands 1 support before adding other games? If not, please do. Previous methods that people used to run multiple windows of Borderlands 1/split screen no longer work. Thanks

**Comment by mirh** [comment]
It wouldn't be bad if you could say which file was detected.

**Comment by RockyStarted** [comment]
Hey, I'm new here but I'm curious about this as well. Does the creator intend to release a version that supports borderlands 1 anytime soon? Also, I should probably create a new issue for this but borderlands tps doesnt work either. As soon as the second player tries to join from the lobby an error appears that says the game is not in the drive. I've just reverted to using the last version of Split Play on his previous site which does work with borderlands tps.

And if he doesnt intend to release a version supporting borderlands 1 soon. Could some one please post a quick tutorial on how to package his code into an exe since he did say he updated the code to work with borderlands 1 already? Thanks a bunch!

**Comment by lucasassislar** [comment]
I thought Borderlands 1 was working but I was mistaken. It ~kinda~ works, but still needs 1 fix to be playable.

About the Trojan, if you could say what file it detected i can explain why its a false positive - theres a ton of libraries that could be detected as false positives.

**Comment by mirh** [comment]
Checking #10 for first wouldn't be bad I guess.
